services:
  - type: web
    name: yt-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    build:
      shell: bash
    shell: bash
    envVars:
      - key: PORT
        value: 10000
